const assert=require('node:assert/strict');
const roles=require('../assets/js/role-interface-core.js');

assert.equal(roles.normalizeRole('Руководитель'),'manager');
assert.equal(roles.normalizeRole('unexpected'),'unknown');
assert.equal(roles.isKnown('unknown'),false);
assert.equal(roles.canRoute('barista','revisions'),true,'barista sees coffee revisions');
assert.equal(roles.canRoute('barista','checklists'),true,'barista sees checklists');
assert.equal(roles.canRoute('barista','attestations'),true,'barista can open assigned Attestations');
assert.equal(roles.canRoute('waiter','checklists'),true,'waiter sees role-specific checklists');
assert.equal(roles.canRoute('waiter','attestations'),true,'waiter can open assigned Attestations');
assert.equal(roles.canRoute('waiter','revisions'),false,'waiter does not see coffee revisions');
assert.equal(roles.canRoute('waiter','tasks'),true,'waiter sees personal tasks');
assert.equal(roles.canRoute('manager','attestations'),false,'manager keeps Attestations results inside Control only');
assert.equal(roles.canRoute('barista','employees'),false,'barista cannot manage employees');
assert.equal(roles.canRoute('waiter','employees'),false,'waiter cannot manage employees');
assert.ok(!roles.homeBlocks('manager').includes('attention'),'manager attention block was intentionally removed');
assert.equal(roles.homeBlocks('barista')[0],'todayWork','barista home starts with actual work for today');
assert.equal(roles.homeBlocks('waiter')[0],'todayWork','waiter home starts with actual work for today');
assert.ok(roles.homeBlocks('barista').includes('coffeeRevision'));
assert.ok(!roles.homeBlocks('waiter').includes('coffeeRevision'));
assert.equal(roles.can('manager','manage_employees'),false,'manager does not inherit admin rights');
assert.equal(roles.canRoute('manager','revisions',{maintenance:true}),false,'maintenance closes manager route');
assert.equal(roles.canRoute('admin','employees'),true,'admin sees all routes');
assert.equal(roles.canRoute('admin','attestations'),true,'admin can manage Attestations');
assert.deepEqual(roles.previewRoles('admin'),['manager','barista','waiter']);
assert.deepEqual(roles.previewRoles('manager'),[]);
assert.equal(roles.canRoute('waiter','employees',{realRole:'admin'}),true,'admin preview never reduces real rights');
assert.equal(roles.canRoute('waiter','employees',{realRole:'waiter'}),false,'employee cannot open admin route directly');
assert.equal(roles.can('waiter','manage_employees'),false,'employee cannot perform admin operation');
assert.equal(roles.canRoute('unknown','employees'),false,'unknown role has no elevated access');
assert.deepEqual(roles.routes('unknown'),['home','tasks'],'unknown role receives safe minimal shell');
assert.equal(roles.canRoute('waiter','tasks',{assigned:true}),true,'personal assignment remains visible');
assert.ok(!roles.navigation('waiter').some(item=>item.id==='revisions'));
assert.ok(roles.navigation('barista').some(item=>item.id==='revisions'));
assert.ok(roles.navigation('barista').some(item=>item.id==='attestations'));
assert.ok(roles.navigation('waiter').some(item=>item.id==='attestations'));
assert.ok(!roles.navigation('manager').some(item=>item.id==='attestations'));
console.log('role-interface-core: role routes and useful home blocks passed');